# Generated by Django 5.2.6 on 2025-09-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ouruser',
            name='number',
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
