# Generated by Django 5.2.6 on 2025-12-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_userfile_file_remove_userfile_last_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='uploaded_file',
            field=models.FileField(default='  ', upload_to='user_files/'),
            preserve_default=False,
        ),
    ]
