# Generated by Django 5.2.6 on 2025-12-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_ouruser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouruser',
            name='editor_theme',
            field=models.CharField(default='vs-dark', max_length=50),
        ),
    ]
