# Generated by Django 5.2.6 on 2025-11-03 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_userfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='size',
        ),
        migrations.AddField(
            model_name='userfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfile',
            name='file_path',
            field=models.CharField(default=1234, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfile',
            name='file_size',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
    ]
