# Generated by Django 5.2.6 on 2025-12-04 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_userfile_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='uploaded_file',
        ),
    ]
