# Generated by Django 5.2.6 on 2025-12-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_userfile_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouruser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/default.png', null=True, upload_to='profile_photos/'),
        ),
    ]
