# Generated by Django 5.2.4 on 2026-03-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_ouruser_editor_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('signup', 'Signup')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('temp_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
