"""
Django settings for pythonEditor project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w+tlf+$aswb13lc5@2+3fq8g_1#&o%jfy+e37+cdafkukf_3+w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Ye batata hai ki URL kya hoga
STATIC_URL = '/static/'
# Ye batata hai ki Render ke server par files kahan save hongi (YE MISSING THA)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Agar aapka static folder hai toh ye line bhi check kar lein
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'mainapp', 'static'),
]

# Application definition

INSTALLED_APPS = [
    'daphne',
    'captcha',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # Add your social providers here
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',

    'editor',
    'mainapp',
    'storages',
]

SITE_ID = 1

AUTH_USER_MODEL = 'mainapp.OurUser'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'pythonEditor.urls'

# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'

# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_URL = '/media/'
# Isse images seedha load hongi



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pythonEditor.wsgi.application'
ASGI_APPLICATION = 'pythonEditor.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379')],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600
    )
}

from django.contrib import admin
from django.urls import path, include


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True




# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'auth'

# Allauth settings
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email' # Agar aap email se primary login chahte hain
ACCOUNT_EMAIL_VERIFICATION = 'none' 

SOCIALACCOUNT_ADAPTER = 'mainapp.adapters.MySocialAccountAdapter'

# Render ke proxy server ko batane ke liye ki connection secure (https) hai
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Aapke domain ko CSRF check ke liye allow karne ke liye
CSRF_TRUSTED_ORIGINS = ['https://pygenix.onrender.com']

# Login ke baad kahan redirect karna hai
LOGIN_REDIRECT_URL = '/dashboard/' # Apne hisaab se URL name ya path dein
LOGOUT_REDIRECT_URL = '/auth/' # Logout hone par kahan jaye
SOCIALACCOUNT_LOGIN_ON_GET = True

# Email configuration for OTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'pygenixeditor@gmail.com'  
EMAIL_HOST_PASSWORD = 'cviw elld pgzh womb'


# Supabase S3 Storage
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = 'media' # Jo naam aapne Supabase bucket ko diya
AWS_S3_ENDPOINT_URL = f"https://{os.environ.get('SUPABASE_PROJECT_ID')}.supabase.co/storage/v1/s3"
AWS_S3_REGION_NAME = 'ap-northeast-1' 
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_ADDRESSING_STYLE = "path"
AWS_S3_VERIFY = True

# to load profile img from supabase
MEDIA_URL = f"https://{os.environ.get('SUPABASE_PROJECT_ID')}.supabase.co/storage/v1/object/public/media/"

# Naye Django versions ke liye ye format best hai
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Purani settings ko force karne ke liye (Backup)
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# Taaki Supabase link expired na dikhaye
AWS_QUERYSTRING_AUTH = False

# 1. Manifest storage ko hata kar normal compressed karein
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# 2. Agar koi file missing ho (jaise .map), toh build fail na kare
WHITENOISE_MANIFEST_STRICT = False
